Testfrom Staging
rndmomentum/crm pull request #1
Opened 2021-07-19 02:18 UTC by mrhery

HI! Please review our staging branch and do few test to see if errors occurs.  We will send another pull request for added features (updated dev branch) on next pull request.

Basic updates:
- Missing Auth
- Sorting layout desgin

2021-07-21 08:57 UTC, rndmomentum approved these changes

2021-07-21 13:19 UTC, rndmomentum approved these changes

2021-07-21 13:20 UTC, rndmomentum approved these changes

2021-07-21 15:20 UTC, rndmomentum requested changes
Semuanya saya dah review

2021-07-22 01:44 UTC, mrhery commented
ok noted

2021-07-22 02:31 UTC, rndmomentum approved these changes
Thanks en hery

2021-07-22 02:32 UTC, rndmomentum approved these changes

2021-07-22 02:32 UTC, rndmomentum approved these changes

2021-07-22 03:46 UTC, merged